//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HQTCSDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDatPhong
    {
        public int MaDatPhong { get; set; }
        public int MaPhong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
    
        public virtual DatPhong DatPhong { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
