//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HQTCSDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhAnhPhong
    {
        public int MaHinh { get; set; }
        public int MaPhong { get; set; }
        public string TenTep { get; set; }
        public string DuongDan { get; set; }
        public string MoTa { get; set; }
    
        public virtual Phong Phong { get; set; }
    }
}
