//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HQTCSDL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QL_KhachSanEntities_ : DbContext
    {
        public QL_KhachSanEntities_()
            : base("name=QL_KhachSanEntities_")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietDatPhong> ChiTietDatPhong { get; set; }
        public virtual DbSet<DanhGia> DanhGia { get; set; }
        public virtual DbSet<DatPhong> DatPhong { get; set; }
        public virtual DbSet<DichVu> DichVu { get; set; }
        public virtual DbSet<HinhAnhPhong> HinhAnhPhong { get; set; }
        public virtual DbSet<HoaDon> HoaDon { get; set; }
        public virtual DbSet<KhachHang> KhachHang { get; set; }
        public virtual DbSet<LoaiPhong> LoaiPhong { get; set; }
        public virtual DbSet<NhanVien> NhanVien { get; set; }
        public virtual DbSet<Phong> Phong { get; set; }
        public virtual DbSet<SuDungDichVu> SuDungDichVu { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoan { get; set; }
        public virtual DbSet<ThanhToan> ThanhToan { get; set; }
    
        public virtual ObjectResult<Nullable<int>> usp_DatPhong_1Phong(Nullable<int> maKH, Nullable<int> maNV, Nullable<int> maPhong, Nullable<System.DateTime> ngayNhan, Nullable<System.DateTime> ngayTra, Nullable<decimal> donGia, string trangThai)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            var maPhongParameter = maPhong.HasValue ?
                new ObjectParameter("MaPhong", maPhong) :
                new ObjectParameter("MaPhong", typeof(int));
    
            var ngayNhanParameter = ngayNhan.HasValue ?
                new ObjectParameter("NgayNhan", ngayNhan) :
                new ObjectParameter("NgayNhan", typeof(System.DateTime));
    
            var ngayTraParameter = ngayTra.HasValue ?
                new ObjectParameter("NgayTra", ngayTra) :
                new ObjectParameter("NgayTra", typeof(System.DateTime));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(decimal));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_DatPhong_1Phong", maKHParameter, maNVParameter, maPhongParameter, ngayNhanParameter, ngayTraParameter, donGiaParameter, trangThaiParameter);
        }
    }
}
