//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HQTCSDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuDungDichVu
    {
        public int MaSDDV { get; set; }
        public int MaDatPhong { get; set; }
        public int MaDV { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<System.DateTime> NgaySD { get; set; }
    
        public virtual DatPhong DatPhong { get; set; }
        public virtual DichVu DichVu { get; set; }
    }
}
