//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HQTCSDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        public int MaTT { get; set; }
        public int MaHD { get; set; }
        public string PhuongThuc { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public string TrangThai { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
    }
}
